services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Jose\Component\Core\JWAManagerFactory: ~
    Jose\Component\Core\JWKFactory: ~
    Jose\Bundle\JoseFramework\Controller\JWKSetControllerFactory: ~
    Jose\Bundle\JoseFramework\Routing\JWKSetLoader:
        tags:
            - {'name': 'routing.loader'}
