language: php

sudo: true

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.1
          env: deps=low
        - php: 7.1
        - php: nightly

before_script:
    - composer self-update
    - mkdir -p build/logs
    - chmod +x ./install_php_ext.sh
    - ./install_php_ext.sh
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - php ./examples/Encrypt1.php
    - php ./examples/Encrypt2.php
    - php ./examples/Signature1.php
    - php ./examples/Signature2.php
    - php ./examples/Load1.php
    - php ./examples/Load2.php
    - php ./examples/Load3.php
    - php ./examples/Load4.php
    - php ./examples/Load4.php
    - php ./examples/NestedTokens.php
    - php ./examples/LoadNestedTokens.php

after_success:
    - vendor/bin/coveralls --no-interaction
