services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Jose\Component\Console\Command\EcKeyGeneratorCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\EcKeysetGeneratorCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\OctKeyGeneratorCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\OctKeysetGeneratorCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\OkpKeyGeneratorCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\OkpKeysetGeneratorCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\RsaKeyGeneratorCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\RsaKeysetGeneratorCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\KeyFileLoaderCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\P12CertificateLoaderCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\X509CertificateLoaderCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\OptimizeRsaKeyCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\JKULoaderCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\X5ULoaderCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\KeyAnalyzerCommand:
        tags:
            - {name: 'console.command'}

    Jose\Component\Console\Command\KeysetAnalyzerCommand:
        tags:
            - {name: 'console.command'}
