services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Jose\Component\KeyManagement\JKUFactory: ~
    Jose\Component\KeyManagement\X5UFactory: ~
    Jose\Bundle\KeyManagement\Service\RequestFactory: ~
    Http\Adapter\Guzzle6\Client: ~
